### ISSUE TITLE
Tiny jpeg not using Arduino IDE

### ISSUE THREAD

**Issue by 5shekel** [anonette/NonFungibleScience#1]
we got a message from MJ that there is issue compiling the code. 

![error](https://user-images.githubusercontent.com/222526/224570821-17ec81c8-b788-4ec5-b144-a0f54e8496ad.jpeg)

@tm4t0 did you encounter this?

i didnt try arduino IDE but instead used platformIO,[branch](https://github.com/anonette/NonFungibleScience/tree/platformio/CAM#using-platformio)*

*(to make platformIO happy i had to change the folder structure a bit. ill see if i can merge to master)

**Comment by yair-mantis** [comment]
[platformIO branch](https://github.com/anonette/NonFungibleScience/tree/platformio)

**Comment by yair-mantis** [comment]
when u include a header like that use "" and not <>. then it will work also in arduino i assume
`include "lala/lala/tjpgd.h"`
